server:
    port: 10000
    context-path: /api
    undertow:
        io-threads: 4
        worker-threads: 20
        buffer-size: 1024
        direct-buffers: true
spring:
    redis:
        hostName: 127.0.0.1
        port: 6379
        database: 0
        password: 123456
        pool:
            maxActive: 10
            maxWait: -1
            maxIdle: 8
            minIdle: 0
        timeout: 0
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/vcl_aggregate
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
        hikari:
            maximum-pool-size: 5
            max-lifetime: 28800
            idle-timeout: 28800
            connection-test-query: SELECT 1 FROM DUAL
            auto-commit: false
